# Generated by Django 4.0.5 on 2022-06-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adjancedmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstCity', models.CharField(max_length=255)),
                ('secondCity', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='heuristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('Hval', models.FloatField()),
            ],
        ),
    ]
